#!/bin/bash

# Copyright (c) 2022 Alex313031

./thorium_shell --data-path=$(pwd)/.config/thorium-shell --enable-experimental-web-platform-features --new-canvas-2d-api --enable-clear-hevc-for-testing $@
