#!/bin/sh
HERE="$(pwd)"
PARENT="$(dirname "$HERE")"
export LD_LIBRARY_PATH="${PARENT}"/lib:$PATH
"${HERE}"/thorium_shell --no-default-browser-check --use-gl=desktop --enable-experimental-web-platform-features --new-canvas-2d-api $@
